### PR TITLE
request - change sourcetype to routeros

### PR DESCRIPTION
**Pull request by nn-df**
Hello,

It is possible to change the sourcetype to "**routeros**"?

### CODE REVIEW

**Comment by Jotne** [comment]
It can be done, but why change it?  Does it crash with some other apps you have?
To change it we need to change it in transforms.conf as well as all dashboards (39) saved search + some other place.
And it would break the app for all data that has been saved over several years for some user, if not change the dashboard to use both old and new sourcetype.
So I would say it should stay with the sourcetype=mikrotik

**Comment by nn-df** [comment]
ok thanks.
i used this sourcetype "routeros" because of this https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Mikrotik/routeros/ . so to used this app do i need to change sourcetype to "mikrotik" right ?

**Comment by Jotne** [comment]
If you like to use this MikroTik app, I do recommend you to change sourcetype to mikrotik.

**Comment by Jotne** [comment]
Will break to much to be an easy fix.

**Pull request closed without merging**
